db_replication_user: artisan_slave_user     #
db_replication_password: artisan_slave_pass #
db_replication_mode: 'slave'                #
db_master_internal_host: 10.129.1.28        #

db_username: artisan                        #
db_password: artisan                        #
db_port: '5432'                             #

db_volume: pg_slave_data                    #
db_volume_path_inside: /db_slave/postgresql #
db_container_name: postgres_slave           #
db_image: bitnami/postgresql                #